=== Michenux/mdk-source-gen/generators/src/main/resources/config/xmlMerge/xmlMerge.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sopragroup.com" xmlns="http://www.sopragroup.com" elementFormDefault="qualified">
	<xs:element name="configuration">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="node" minOccurs="1" maxOccurs="unbounded">
	      	  <xs:complexType>
			    <xs:attribute name="name" type="xs:string" use="required" />
			    <xs:attribute name="idAttribute" type="xs:string" use="optional"/>
			    <xs:attribute name="identificationType" type="identificationTypeType" use="required"/>
			    <xs:attribute name="content" type="contentType" use="required"/>	      	  
		      </xs:complexType>
	      </xs:element>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>


<xs:simpleType name="identificationTypeType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="root"/>
    <xs:enumeration value="keyForSibling"/>
    <xs:enumeration value="name"/>
    <xs:enumeration value="name+attr"/>
    <xs:enumeration value="parent+name"/>
    <xs:enumeration value="parent+name+attr"/>
    <xs:enumeration value="parent+name+siblingKey"/>
    <xs:enumeration value="parent+name+attr|value"/>
  </xs:restriction>
</xs:simpleType>
<xs:simpleType name="contentType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="none"/>
    <xs:enumeration value="children"/>
    <xs:enumeration value="text"/>
    <xs:enumeration value="text+children"/>
  </xs:restriction>
</xs:simpleType>

</xs:schema>

=== Michenux/mdk-source-gen/generators/src/main/resources/config/xmlMerge/ios/coredata.xml
<!--

    Copyright (C) 2010 Sopra Steria Group (movalys.support@soprasteria.com)

    This file is part of Movalys MDK.
    Movalys MDK is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Movalys MDK is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Lesser General Public License for more details.
    You should have received a copy of the GNU Lesser General Public License
    along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.

-->
<configuration xmlns="http://www.sopragroup.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.sopragroup.com ../xmlMerge.xsd">
	<node name="model"							identificationType="root" 														content="children"	/>
	<node name="entity"							identificationType="name+attr"					idAttribute="name"				content="children"	/>
	<node name="attribute"						identificationType="parent+name+attr"			idAttribute="name"				content="none"	/>
	<node name="relationship"					identificationType="parent+name+attr"			idAttribute="name"				content="none"	/>
	<node name="fetchedProperty"				identificationType="parent+name+attr"			idAttribute="name"				content="children"	/>
	<node name="fetchRequest"					identificationType="parent+name+attr"			idAttribute="name"				content="none"	/>
	<node name="configuration"					identificationType="name+attr"					idAttribute="name"				content="children"	/>
	<node name="memberEntity"					identificationType="parent+name+attr"			idAttribute="name"				content="none"	/>
	<node name="elements"						identificationType="name"														content="children"	/>
	<node name="element"						identificationType="name+attr"					idAttribute="name"				content="none"	/>
</configuration>

=== Michenux/mdk-source-gen/generators/src/main/resources/config/xmlMerge/ios/xib_xcode4.xml
<!--

    Copyright (C) 2010 Sopra Steria Group (movalys.support@soprasteria.com)

    This file is part of Movalys MDK.
    Movalys MDK is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Movalys MDK is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Lesser General Public License for more details.
    You should have received a copy of the GNU Lesser General Public License
    along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.

-->
<!-- This XML file is to open with the Eclipse plugin "Rinzo"-->
<configuration xmlns="http://www.sopragroup.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.sopragroup.com ../xmlMerge.xsd">
	<node name="archive"						identificationType="root" 														content="children"	/>
	<node name="data"							identificationType="name"														content="children"	/>
	<node name="bool"							identificationType="parent+name+attr|value"		idAttribute="id|key"			content="text"	/>
	<node name="boolean"						identificationType="parent+name+attr|value"		idAttribute="id|key"			content="text"	/>
	<node name="int"							identificationType="parent+name+attr|value" 	idAttribute="id|key"			content="text"	/>
	<node name="integer"						identificationType="parent+name+attr|value" 	idAttribute="id|key"			content="text"	/>
	<node name="float"							identificationType="parent+name+attr|value" 	idAttribute="id|key"			content="text"	/>
	<node name="real"							identificationType="parent+name+attr|value" 	idAttribute="id|key"			content="text"	/>
	<node name="double"							identificationType="parent+name+attr|value" 	idAttribute="id|key"			content="text"	/>
	<node name="string"							identificationType="parent+name+attr|value"		idAttribute="id|key"			content="text"	/>
	<node name="bytes"							identificationType="parent+name+attr|value" 	idAttribute="id|key"			content="text"	/>
	<node name="nil"							identificationType="parent+name+attr|value" 	idAttribute="id|key"			content="none"	/>
	<node name="reference"						identificationType="parent+name+attr"		 	idAttribute="key"				content="none"	/>
	<node name="object"							identificationType="parent+name+attr" 			idAttribute="key"				content="children"	/>
	<node name="array"							identificationType="parent+name+attr" 			idAttribute="id"				content="children"	/>
</configuration>

=== Michenux/mdk-source-gen/generators/src/test/resources/config/xmlMerge/tests/conf-plist.xml
<!--

    Copyright (C) 2010 Sopra Steria Group (movalys.support@soprasteria.com)

    This file is part of Movalys MDK.
    Movalys MDK is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Movalys MDK is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Lesser General Public License for more details.
    You should have received a copy of the GNU Lesser General Public License
    along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.

-->
<configuration xmlns="http://www.sopragroup.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.sopragroup.com ../xmlMerge.xsd">
	<node name="plist"							identificationType="root" 												content="children"	/>
	<node name="dict"							identificationType="name+attr"				idAttribute="key" 			content="children"	/>
	<node name="dummy"							identificationType="keyForSibling"			idAttribute="key" 			content="children"	/>
	<node name="artificialGroupingForXmlMerge"	identificationType="name+attr"				idAttribute="key" 			content="children"	/>
	<node name="key"							identificationType="parent+name"										content="text"	/>
	<node name="string"							identificationType="parent+name"										content="text"	/>
	<node name="true"							identificationType="parent+name"										content="none"	/>
	<node name="false"							identificationType="parent+name"										content="none"	/>
	<node name="integer"						identificationType="parent+name"										content="text"	/>
	<node name="array"							identificationType="parent+name"										content="children"	/>
	<node name="data"							identificationType="parent+name"										content="text"	/>
	<node name="date"							identificationType="parent+name"										content="text"	/>
</configuration>

=== Michenux/mdk-source-gen/generators/src/test/resources/config/xmlMerge/tests/conf.xml
<!--

    Copyright (C) 2010 Sopra Steria Group (movalys.support@soprasteria.com)

    This file is part of Movalys MDK.
    Movalys MDK is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Movalys MDK is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Lesser General Public License for more details.
    You should have received a copy of the GNU Lesser General Public License
    along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.

-->
<configuration xmlns="http://www.sopragroup.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.sopragroup.com ../xmlMerge.xsd">
	<node name="tests" identificationType="root"/>
	<node name="testA" identificationType="name+attr" idAttribute="id"/>
	<node name="testAA" identificationType="name+attr" idAttribute="id"/>
	<node name="testB" identificationType="name+attr" idAttribute="idB"/>
	<node name="testC" identificationType="name+attr" idAttribute="idC"/>
	<node name="testD" identificationType="name+attr" idAttribute="idD"/>
	<node name="testE" identificationType="name+attr" idAttribute="idE"/>
	<node name="testF" identificationType="name+attr" idAttribute="idF"/>
	<node name="testG" identificationType="name+attr" idAttribute="idG"/>
	<node name="testGG" identificationType="name+attr" idAttribute="id"/>
	<node name="testH" identificationType="name+attr" idAttribute="id"/>
	<node name="testH2" identificationType="name+attr" idAttribute="id"/>
	<node name="testHH" identificationType="name+attr" idAttribute="idH"/>
	<node name="testZZ" identificationType="parent+name" />
	<node name="testZZ2" identificationType="parent+name" />
	<node name="testZZ3" identificationType="parent+name" />
	<node name="testZZ4" identificationType="parent+name" />
	<node name="testQ" idAttribute="ref" identificationType="parent+name+attr" />
</configuration>

=== Michenux/mdk-source-gen/generators/src/main/resources/config/xmlMerge/android/manifest.xml
<!--

    Copyright (C) 2010 Sopra Steria Group (movalys.support@soprasteria.com)

    This file is part of Movalys MDK.
    Movalys MDK is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Movalys MDK is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Lesser General Public License for more details.
    You should have received a copy of the GNU Lesser General Public License
    along with Movalys MDK. If not, see <http://www.gnu.org/licenses/>.

-->
<configuration xmlns="http://www.sopragroup.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.sopragroup.com ../xmlMerge.xsd">
	<node name="manifest"			identificationType="root" 													content="children"	/>
	<node name="application"		identificationType="name" 													content="children"	/>
	<node name="action" 			identificationType="parent+name+attr" 	idAttribute="android:name"			content="none"		/>
	<node name="activity"			identificationType="name+attr" 			idAttribute="android:name" 			content="children"	/>
	<node name="activity-alias"		identificationType="name+attr" 			idAttribute="android:name" 			content="children"	/>
	<node name="category" 			identificationType="parent+name+attr"	idAttribute="android:name"			content="none"		/>
	<node name="data" 				identificationType="parent+name+attr"	idAttribute="android:scheme|android:host|android:port|android:path|android:pathPattern|android:pathPrefix|android:mimeType"	content="none"/>
	<node name="grant-uri-permission" identificationType="parent+name"											content="none"		/>
	<node name="instrumentation" 	identificationType="name+attr"			idAttribute="android:name"			content="none"		/>
	<node name="intent-filter" 		identificationType="parent+name"											content="children"	/>
	<node name="meta-data" 			identificationType="parent+name"											content="none"		/>
	<node name="path-permission"	identificationType="parent+name"											content="none"		/>
	<node name="permission"			identificationType="name+attr"			idAttribute="android:name"			content="none"		/>
	<node name="permission-group"	identificationType="name+attr"			idAttribute="android:name"			content="none"		/>
	<node name="permission-tree"	identificationType="name+attr"			idAttribute="android:name"			content="none"		/>
	<node name="provider"			identificationType="name+attr"			idAttribute="android:name"			content="children"	/>
	<node name="receiver"			identificationType="name+attr"			idAttribute="android:name"			content="children"	/>
	<node name="service"			identificationType="name+attr"			idAttribute="android:name"			content="children"	/>
	<node name="supports-screens"	identificationType="name"													content="none"		/>
	<node name="uses-configuration"	identificationType="name"													content="none"		/>
	<node name="uses-feature"		identificationType="name+attr"			idAttribute="android:name"			content="none"		/>
	<node name="uses-library"		identificationType="name+attr"			idAttribute="android:name"			content="none"		/>
	<node name="uses-permission"	identificationType="name+attr"			idAttribute="android:name"			content="none"		/>
	<node name="uses-sdk"			identificationType="name"													content="none"		/>
</configuration>
